name: Test and Deploy

on:
  pull_request:

jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # GOPATH等のセットアップ
      - name: Set Up
        uses: actions/setup-go@v2
        with:
          go-version: ~1.15

      # repositoryの中身にアクセスするためにチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # 実行
      - name: Run
        run: go run main.go
