name: Test and Deploy

on:
  pull_request:

jobs:
  run:
    name: Test
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display hello world pwsh
        run: |
          Start-Process -FilePath "main.exe"
          $PSVersionTable
        shell: pwsh
